version: "3.9"
services:
  bot:
    build: .
    environment: 
      DISCORD_TOKEN:
  mongo:
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - "27017"
